export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_COMPLETE_TODO = "TOGGLE_COMPLETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const CLEAR_ALL_TODOS = "CLEAR_ALL_TODOS";
export const TOGGLE_COMPLETE_ALL_TODOS = "TOGGLE_COMPLETE_ALL_TODOS";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
